[package]
name = "devtools"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
name = "devtools"
path = "lib.rs"

[dependencies]
devtools_traits = {path = "../devtools_traits"}
encoding = "0.2"
hyper = {version = "0.9.9", default-features = false}
# hyper_serde = {version = "0.1.4", default-features = false}
hyper_serde = {git = "https://github.com/frewsxcv/hyper_serde.git", branch = "bump-cookie"}
ipc-channel = "0.5"
log = "0.3.5"
msg = {path = "../msg"}
plugins = {path = "../plugins"}
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
time = "0.1"
util = {path = "../util"}
